name: testing

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install tox
        run: |
          python -m pip install tox
      - name: Lint
        run: tox -e lint

  test:
    strategy:
      matrix:
        python:
        - "3.8"
        - "3.9"
        - "3.10"
        # - "3.11"
        # Workaround for actions/setup-python#508
        dev:
        - -dev
        platform:
        - ubuntu-latest
        - macos-latest
        - windows-latest
        include:
        - python: pypy3.9
          platform: ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}${{ matrix.dev }}
      - name: Install pytest
        run: |
          python -m pip install pytest pytest-cov
      - name: Run tests
        run: |
          pip install -e .
          pytest --cov=src/pyEQL --cov-report=xml
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install tox
        run: |
          python -m pip install tox
      - name: Build docs
        run: tox -e docs
